### ISSUE TITLE
Reorganize examples

### ISSUE THREAD

**Issue by gadomski** [stactools-packages/esa-cci-lc#4]
A couple of notes about the `examples/` directory:

- We should reorganize the layout to match the best practices, i.e. items in their own folders, named by ID
- We should use relative paths for all links (save the collection as SELF_CONTAINED) to allow crawling of the examples by e.g. stac-browser

**Comment by m-mohr** [comment]
Regarding the first point, I don't agree because we don't do that in any repo I'm aware of. Not even the stac-spec examples itself do that, I think. We also don't have assets in the examples so the main reason for putting them in folders doesn't apply. It would be just one file per folder, which is weird.

+1 on the relative paths, that's also something that I think I could apply to most of the other packages I've written...

**Comment by gadomski** [comment]
For an example of point #1, https://github.com/stactools-packages/noaa-cdr/blob/main/examples/catalog.json. While I agree it's weird to have a folder w/ a single item in it w/o assets, IMO it's a standard enough layout that it's _not_ weird, at least to my eye. But I'm newer to the ecosystem.

**Comment by m-mohr** [comment]
There it makes more sense because the examples include the assets. IMHO folders don't make sense when there only one file included, but if you'd prefer it I can do that of course (I assume in all repos then?)

**Comment by gadomski** [comment]
> IMHO folders don't make sense when there only one file included, but if you'd prefer it I can do that of course (I assume in all repos then?)

Yeah, if you don't mind, thanks.

**Comment by m-mohr** [comment]
Okay. Nevertheless, I've opened https://github.com/radiantearth/stac-spec/issues/1195 to get a common understanding how we want to handle the case where we don't have any additional files for the Item ;-)

**Comment by m-mohr** [comment]
Reorganized
